/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theatrebookingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static theatrebookingsystem.LoginUI.role_id;
import static theatrebookingsystem.LoginUI.roles;

/**
 *
 * @author User
 */
public class ChangeMovies extends javax.swing.JFrame {

    /**
     * Creates new form AddAdmin
     */
    public ChangeMovies() {
        initComponents();
        setSize(440,380);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Change Movies");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(124, 24, 188, 51);

        jLabel2.setText("Old Movie");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(47, 111, 79, 28);

        jLabel4.setText("New Movie");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(47, 184, 79, 31);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(188, 113, 173, 24);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(188, 184, 173, 24);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 260, 77, 32);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\PROJECT\\TheatreBookingSystem\\ss\\Bloody Mary.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, -4, 440, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    static int role_id = 0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username = "root";
       String password = "Lachu123@#";
       String url = "jdbc:mysql://127.0.0.1:3306/theatre_booking";
       
       try{
               String query2 = "select * from movies  where movie_name=?";
               Connection connect1 = DriverManager.getConnection(url,username,password);
               PreparedStatement ps3 = connect1.prepareStatement(query2); //PS1 PREPARED STATEMENT
               ps3.setString(1,jTextField1.getText());
               ResultSet rset3 = ps3.executeQuery();
                
               if(rset3.next()){
                  role_id = rset3.getInt("movie_id");
                  System.out.println("movie_id : "+role_id);
              }
              }catch(Exception e1){
                  System.out.println("error in movie_id");
              }
       
       
       
       try{
               String query3 = " UPDATE movies set movie_name=? where movie_id=?";
               Connection connect = DriverManager.getConnection(url,username,password);
               PreparedStatement ps4 = connect.prepareStatement(query3); //PS1 PREPARED STATEMENT
               ps4.setString(1,jTextField2.getText());
               ps4.setInt(2,role_id);
               ps4.execute();
                
               
               JOptionPane.showMessageDialog(rootPane, "Updated Successfully");
                   
                 
              
              }catch(Exception e){
                  System.out.println("error in updated");
              }
                dispose();
                new MenuForm().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeMovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
