/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theatrebookingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import static theatrebookingsystem.LoginUI.role_id;
import static theatrebookingsystem.LoginUI.roles;

/**
 *
 * @author User
 */
public class PaymentForm extends javax.swing.JFrame {

    /**
     * Creates new form PaymentForm
     */
    public PaymentForm() {
        initComponents();
        setSize(1000,520);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    static ArrayList<String> seats = new ArrayList<String>();
    String username = "root";
    String password = "Lachu123@#";
    String url = "jdbc:mysql://127.0.0.1:3306/theatre_booking";
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie", "Date", "Seats", "Payment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(46, 124, 920, 160);

        jLabel1.setBackground(new java.awt.Color(0, 204, 153));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payments");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 40, 284, 46);

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(26, 33, 51, 46);

        jButton2.setText("Generate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 340, 120, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\PROJECT\\TheatreBookingSystem\\ss\\Bloody Mary.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, -4, 1020, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = "root";
        String password = "Lachu123@#";
         String url = "jdbc:mysql://127.0.0.1:3306/theatre_booking";
         try{
               String query3 = "SELECT * FROM roles where role_name=? and role_id=?";
               Connection connect = DriverManager.getConnection(url,username,password);
               PreparedStatement ps4 = connect.prepareStatement(query3); //PS1 PREPARED STATEMENT
               ps4.setString(1,LoginUI.usertext.getText());
               ps4.setInt(2,role_id);
               ResultSet rset2 = ps4.executeQuery();
                
               if(rset2.next()){
                 roles = rset2.getString("role_desc");
                 
              }
               System.out.println("role_desc : "+roles);
              }catch(Exception e){
                  System.out.println("error in roles");
              }
       
         if(roles.equals("customers")){
             dispose();
             MenuForm menu = new MenuForm();
              menu.jButton5.setEnabled(false);
              menu.setVisible(true);
         }else{
               dispose();
               new MenuForm().setVisible(true);

         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         HashMap<Integer,String> movies = new HashMap<Integer,String>();
        movies.put(1,"Batman Dark Knight");
        movies.put(2,"The Expandables");
        movies.put(3,"Fight Club");
        movies.put(4,"Ford Vs Ferrari");
        movies.put(5,"Forrest Gump");
        movies.put(6,"The Hangover");
        movies.put(7,"John Wick");
        movies.put(8,"Jurassic park");
        movies.put(9,"Predator");
        movies.put(10,"Titanic");
        
        String username = "root";
        String password = "Lachu123@#";
        String url = "jdbc:mysql://127.0.0.1:3306/theatre_booking";
        
        try{
            Connection con = DriverManager.getConnection(url,username,password);
            String query = "select * from payment where pay_cus_id=? ";
            PreparedStatement psmt = con.prepareStatement(query);
            psmt.setInt(1,LoginUI.user_id);
            ResultSet rs = psmt.executeQuery();
            
            
           
            int movieid =0; 
            Timestamp date = new Timestamp(System.currentTimeMillis());
            String movieName = "";
            String movieseats ="";
            int pays = 0;
            
            
            
            while(rs.next()){
               movieid = rs.getInt("movieid");
               date = rs.getTimestamp("pay_date");
               for(Map.Entry<Integer,String> entry : movies.entrySet()){
                   if(rs.getInt("movieid") == entry.getKey()){
                       movieName = entry.getValue();
                   }
               }
               pays = rs.getInt("pay_amount");
             
               
             
               DateFormat df = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
              
               
               
               if(date!=rs.getTimestamp("pay_date")){
                   ArrayList<String > seats1 = getSeatNames(date,LoginUI.user_id,movieid);
                    System.out.println("MOVIE SEATS :"+seats1.toString());
                   String selectseat = " ";
                   for(String s : seats1){
                       selectseat = s + " "+selectseat;
                   }
                   
                   String str []= {movieName,df.format(date),selectseat,String.valueOf(pays)};
                   DefaultTableModel tblModel = (DefaultTableModel) PaymentForm.jTable1.getModel();
                   tblModel.addRow(str);
                                     
                   
                   date = rs.getTimestamp("pay_date");
                   movieseats = " ";
                   movieid = rs.getInt("movieid");
                   seats1.clear();
                   seats.clear();
               }
            }
            
        }catch(Exception e){
             System.out.println("Some errirs are there");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public ArrayList<String> getSeatNames(Timestamp date, int user_id, int movieid) throws SQLException {
        String username = "root";
        String password = "Lachu123@#";
        String url = "jdbc:mysql://127.0.0.1:3306/theatre_booking";
        Connection con1 = DriverManager.getConnection(url,username,password);
        String query1 = "select * from seatbook where USERID=? and MOVIEID=?";
        PreparedStatement psmt1 = con1.prepareStatement(query1);
        psmt1.setInt(1,user_id);
        psmt1.setInt(2,movieid);
        ResultSet rs1 = psmt1.executeQuery();
        while(rs1.next()){
            seats.add(rs1.getString("SEATNAMES"));
            System.out.println(rs1.getString("seatnames"));
        }
        
       for(String s : seats){
           System.out.println(s);
       }
        return seats;
    }
}
