/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theatrebookingsystem;
import theatrebookingsystem.LoginUI;
import theatrebookingsystem.MovieCollection;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JButton;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.Date;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import static java.util.Map.entry;
import javax.swing.JComboBox;
/**
 *
 * @author 2018/E/070
 */
public class SeatBook extends javax.swing.JFrame {

    /**
     * Creates new form SeatBook
     */
    public SeatBook() {
        initComponents();
        setSize(840,520);
        setLocation(350,150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    static Color normalColor = new Color(204,204,204);
    static ArrayList<JButton> buttons = new ArrayList<JButton>(); //click select and unselect
    static ArrayList<String> seatNames = new ArrayList<String>();//add name into textField
    static int price = 0;
    static String movieName = MovieCollection.movie_Name;
    static HashMap<JButton,String> seats = new HashMap<JButton,String>();
    ArrayList<String> temp = new ArrayList<String>();
    
    
    String username = "root";
    String password = "Lachu123@#";
    String url = "jdbc:mysql://127.0.0.1:3306/theatre_booking";
    

    
    
    
    
    public static void selectUnSelect(JButton jButton,int p){
        if(jButton.getModel().isSelected()==false){
            jButton.setBackground(Color.GREEN);
            buttons.add(jButton);
            seatNames.add(jButton.getName());
            showSeatNames(seatNames);
            jButton.getModel().setSelected(true);
            price += p;
            jTextField2.setText(Integer.toString(price));
            
            
            
            
        }else if(jButton.getModel().isSelected()==true){
            jButton.setBackground(normalColor);
//            jButton.getClass().getDef;
            buttons.remove(jButton);
            seatNames.remove(jButton.getName());
            showSeatNames(seatNames);
            jButton.setSelected(false);
            price-=p;
            jTextField2.setText(Integer.toString(price));
            
        }
    }
    
    
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        seat25 = new javax.swing.JButton();
        seat11 = new javax.swing.JButton();
        seat13 = new javax.swing.JButton();
        seat14 = new javax.swing.JButton();
        seat15 = new javax.swing.JButton();
        seat22 = new javax.swing.JButton();
        seat21 = new javax.swing.JButton();
        seat23 = new javax.swing.JButton();
        seat24 = new javax.swing.JButton();
        seat31 = new javax.swing.JButton();
        seat32 = new javax.swing.JButton();
        seat33 = new javax.swing.JButton();
        seat34 = new javax.swing.JButton();
        seat35 = new javax.swing.JButton();
        seat41 = new javax.swing.JButton();
        seat42 = new javax.swing.JButton();
        seat43 = new javax.swing.JButton();
        seat44 = new javax.swing.JButton();
        seat45 = new javax.swing.JButton();
        seat51 = new javax.swing.JButton();
        seat52 = new javax.swing.JButton();
        seat53 = new javax.swing.JButton();
        seat54 = new javax.swing.JButton();
        seat55 = new javax.swing.JButton();
        seat16 = new javax.swing.JButton();
        seat17 = new javax.swing.JButton();
        seat18 = new javax.swing.JButton();
        seat19 = new javax.swing.JButton();
        seat110 = new javax.swing.JButton();
        seat26 = new javax.swing.JButton();
        seat27 = new javax.swing.JButton();
        seat28 = new javax.swing.JButton();
        seat29 = new javax.swing.JButton();
        seat210 = new javax.swing.JButton();
        seat36 = new javax.swing.JButton();
        seat37 = new javax.swing.JButton();
        seat38 = new javax.swing.JButton();
        seat39 = new javax.swing.JButton();
        seat310 = new javax.swing.JButton();
        seat46 = new javax.swing.JButton();
        seat47 = new javax.swing.JButton();
        seat48 = new javax.swing.JButton();
        seat49 = new javax.swing.JButton();
        seat410 = new javax.swing.JButton();
        seat56 = new javax.swing.JButton();
        seat57 = new javax.swing.JButton();
        seat58 = new javax.swing.JButton();
        seat59 = new javax.swing.JButton();
        seat510 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        seatTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton51 = new javax.swing.JButton();
        seat61 = new javax.swing.JButton();
        seat62 = new javax.swing.JButton();
        seat63 = new javax.swing.JButton();
        seat64 = new javax.swing.JButton();
        seat65 = new javax.swing.JButton();
        seat66 = new javax.swing.JButton();
        seat67 = new javax.swing.JButton();
        seat68 = new javax.swing.JButton();
        seat69 = new javax.swing.JButton();
        seat610 = new javax.swing.JButton();
        seat71 = new javax.swing.JButton();
        seat72 = new javax.swing.JButton();
        seat73 = new javax.swing.JButton();
        seat74 = new javax.swing.JButton();
        seat75 = new javax.swing.JButton();
        seat76 = new javax.swing.JButton();
        seat77 = new javax.swing.JButton();
        seat78 = new javax.swing.JButton();
        seat12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\PROJECT\\TheatreBookingSystem\\ss\\brandi-redd-aJTiW00qqtI-unsplash.jpg")); // NOI18N
        jLabel6.getAccessibleContext().setAccessibleName("bgLabel");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCREEN");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 410, 46);

        seat25.setBackground(new java.awt.Color(204, 204, 204));
        seat25.setText("5");
        seat25.setName("seat25"); // NOI18N
        seat25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat25ActionPerformed(evt);
            }
        });
        getContentPane().add(seat25);
        seat25.setBounds(230, 140, 40, 40);
        seats.put(seat25, seat25.getName());

        seat11.setBackground(new java.awt.Color(204, 204, 204));
        seat11.setText("1");
        seat11.setName("seat11"); // NOI18N
        seat11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat11ActionPerformed(evt);
            }
        });
        getContentPane().add(seat11);
        seat11.setBounds(30, 90, 40, 40);
        seat11.getAccessibleContext().setAccessibleName("");
        seats.put(seat11, seat11.getName());

        seat13.setBackground(new java.awt.Color(204, 204, 204));
        seat13.setText("3");
        seat13.setName("seat13"); // NOI18N
        seat13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat13ActionPerformed(evt);
            }
        });
        getContentPane().add(seat13);
        seat13.setBounds(130, 90, 40, 40);
        seat13.getAccessibleContext().setAccessibleName("");
        seats.put(seat13, seat13.getName());

        seat14.setBackground(new java.awt.Color(204, 204, 204));
        seat14.setText("4");
        seat14.setName("seat14"); // NOI18N
        seat14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat14ActionPerformed(evt);
            }
        });
        getContentPane().add(seat14);
        seat14.setBounds(180, 90, 40, 40);
        seat14.getAccessibleContext().setAccessibleName("");
        seats.put(seat14, seat14.getName());

        seat15.setBackground(new java.awt.Color(204, 204, 204));
        seat15.setText("5");
        seat15.setName("seat15"); // NOI18N
        seat15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat15ActionPerformed(evt);
            }
        });
        getContentPane().add(seat15);
        seat15.setBounds(230, 90, 40, 40);
        seat15.getAccessibleContext().setAccessibleName("");
        seats.put(seat15, seat15.getName());

        seat22.setBackground(new java.awt.Color(204, 204, 204));
        seat22.setText("2");
        seat22.setName("seat22"); // NOI18N
        seat22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat22ActionPerformed(evt);
            }
        });
        getContentPane().add(seat22);
        seat22.setBounds(80, 140, 40, 40);
        seats.put(seat22, seat22.getName());

        seat21.setBackground(new java.awt.Color(204, 204, 204));
        seat21.setText("1");
        seat21.setName("seat21"); // NOI18N
        seat21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat21ActionPerformed(evt);
            }
        });
        getContentPane().add(seat21);
        seat21.setBounds(30, 140, 40, 40);
        seats.put(seat21, seat21.getName());

        seat23.setBackground(new java.awt.Color(204, 204, 204));
        seat23.setText("3");
        seat23.setName("seat23"); // NOI18N
        seat23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat23ActionPerformed(evt);
            }
        });
        getContentPane().add(seat23);
        seat23.setBounds(130, 140, 40, 40);
        seats.put(seat23, seat23.getName());

        seat24.setBackground(new java.awt.Color(204, 204, 204));
        seat24.setText("4");
        seat24.setName("seat24"); // NOI18N
        seat24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat24ActionPerformed(evt);
            }
        });
        getContentPane().add(seat24);
        seat24.setBounds(180, 140, 40, 40);
        seats.put(seat24, seat24.getName());

        seat31.setBackground(new java.awt.Color(204, 204, 204));
        seat31.setText("1");
        seat31.setName("seat31"); // NOI18N
        seat31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat31ActionPerformed(evt);
            }
        });
        getContentPane().add(seat31);
        seat31.setBounds(30, 190, 40, 40);
        seats.put(seat31, seat31.getName());

        seat32.setBackground(new java.awt.Color(204, 204, 204));
        seat32.setText("2");
        seat32.setName("seat32"); // NOI18N
        seat32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat32ActionPerformed(evt);
            }
        });
        getContentPane().add(seat32);
        seat32.setBounds(80, 190, 40, 40);
        seats.put(seat32, seat32.getName());

        seat33.setBackground(new java.awt.Color(204, 204, 204));
        seat33.setText("3");
        seat33.setName("seat33"); // NOI18N
        seat33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat33ActionPerformed(evt);
            }
        });
        getContentPane().add(seat33);
        seat33.setBounds(130, 190, 40, 40);
        seats.put(seat33, seat33.getName());

        seat34.setBackground(new java.awt.Color(204, 204, 204));
        seat34.setText("4");
        seat34.setName("seat34"); // NOI18N
        seat34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat34ActionPerformed(evt);
            }
        });
        getContentPane().add(seat34);
        seat34.setBounds(180, 190, 40, 40);
        seats.put(seat34, seat34.getName());

        seat35.setBackground(new java.awt.Color(204, 204, 204));
        seat35.setText("5");
        seat35.setName("seat35"); // NOI18N
        seat35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat35ActionPerformed(evt);
            }
        });
        getContentPane().add(seat35);
        seat35.setBounds(230, 190, 40, 40);
        seats.put(seat35, seat35.getName());

        seat41.setBackground(new java.awt.Color(204, 204, 204));
        seat41.setText("1");
        seat41.setName("seat41"); // NOI18N
        seat41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat41ActionPerformed(evt);
            }
        });
        getContentPane().add(seat41);
        seat41.setBounds(30, 240, 40, 40);
        seats.put(seat41,seat41.getName());

        seat42.setBackground(new java.awt.Color(204, 204, 204));
        seat42.setText("2");
        seat42.setName("seat42"); // NOI18N
        seat42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat42ActionPerformed(evt);
            }
        });
        getContentPane().add(seat42);
        seat42.setBounds(80, 240, 40, 40);
        seats.put(seat42,seat42.getName());

        seat43.setBackground(new java.awt.Color(204, 204, 204));
        seat43.setText("3");
        seat43.setName("seat43"); // NOI18N
        seat43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat43ActionPerformed(evt);
            }
        });
        getContentPane().add(seat43);
        seat43.setBounds(130, 240, 40, 40);
        seats.put(seat43,seat43.getName());

        seat44.setBackground(new java.awt.Color(204, 204, 204));
        seat44.setText("4");
        seat44.setName("seat44"); // NOI18N
        seat44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat44ActionPerformed(evt);
            }
        });
        getContentPane().add(seat44);
        seat44.setBounds(180, 240, 40, 40);
        seats.put(seat44,seat44.getName());

        seat45.setBackground(new java.awt.Color(204, 204, 204));
        seat45.setText("5");
        seat45.setName("seat45"); // NOI18N
        seat45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat45ActionPerformed(evt);
            }
        });
        getContentPane().add(seat45);
        seat45.setBounds(230, 240, 40, 40);
        seats.put(seat45,seat45.getName());

        seat51.setBackground(new java.awt.Color(204, 204, 204));
        seat51.setText("1");
        seat51.setName("seat51"); // NOI18N
        seat51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat51ActionPerformed(evt);
            }
        });
        getContentPane().add(seat51);
        seat51.setBounds(30, 290, 40, 40);
        seats.put(seat51,seat51.getName());

        seat52.setBackground(new java.awt.Color(204, 204, 204));
        seat52.setText("2");
        seat52.setName("seat52"); // NOI18N
        seat52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat52ActionPerformed(evt);
            }
        });
        getContentPane().add(seat52);
        seat52.setBounds(80, 290, 40, 40);
        seats.put(seat52,seat52.getName());

        seat53.setBackground(new java.awt.Color(204, 204, 204));
        seat53.setText("3");
        seat53.setName("seat53"); // NOI18N
        seat53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat53ActionPerformed(evt);
            }
        });
        getContentPane().add(seat53);
        seat53.setBounds(130, 290, 40, 40);
        seats.put(seat53,seat53.getName());

        seat54.setBackground(new java.awt.Color(204, 204, 204));
        seat54.setText("4");
        seat54.setName("seat54"); // NOI18N
        seat54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat54ActionPerformed(evt);
            }
        });
        getContentPane().add(seat54);
        seat54.setBounds(180, 290, 40, 40);
        seats.put(seat54,seat54.getName());

        seat55.setBackground(new java.awt.Color(204, 204, 204));
        seat55.setText("5");
        seat55.setName("seat55"); // NOI18N
        seat55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat55ActionPerformed(evt);
            }
        });
        getContentPane().add(seat55);
        seat55.setBounds(230, 290, 40, 40);
        seats.put(seat55,seat55.getName());

        seat16.setBackground(new java.awt.Color(204, 204, 204));
        seat16.setText("6");
        seat16.setName("seat16"); // NOI18N
        seat16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat16ActionPerformed(evt);
            }
        });
        getContentPane().add(seat16);
        seat16.setBounds(290, 90, 40, 40);
        seats.put(seat16, seat16.getName());

        seat17.setBackground(new java.awt.Color(204, 204, 204));
        seat17.setText("7");
        seat17.setName("seat17"); // NOI18N
        seat17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat17ActionPerformed(evt);
            }
        });
        getContentPane().add(seat17);
        seat17.setBounds(340, 90, 40, 40);
        seats.put(seat17, seat17.getName());

        seat18.setBackground(new java.awt.Color(204, 204, 204));
        seat18.setText("8");
        seat18.setName("seat18"); // NOI18N
        seat18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat18ActionPerformed(evt);
            }
        });
        getContentPane().add(seat18);
        seat18.setBounds(390, 90, 40, 40);
        seats.put(seat18, seat18.getName());

        seat19.setBackground(new java.awt.Color(204, 204, 204));
        seat19.setText("9");
        seat19.setName("seat19"); // NOI18N
        seat19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat19ActionPerformed(evt);
            }
        });
        getContentPane().add(seat19);
        seat19.setBounds(440, 90, 40, 40);
        seats.put(seat19, seat19.getName());

        seat110.setBackground(new java.awt.Color(204, 204, 204));
        seat110.setText("0");
        seat110.setName("seat110"); // NOI18N
        seat110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat110ActionPerformed(evt);
            }
        });
        getContentPane().add(seat110);
        seat110.setBounds(490, 90, 40, 40);
        seats.put(seat110, seat110.getName());

        seat26.setBackground(new java.awt.Color(204, 204, 204));
        seat26.setText("6");
        seat26.setName("seat26"); // NOI18N
        seat26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat26ActionPerformed(evt);
            }
        });
        getContentPane().add(seat26);
        seat26.setBounds(290, 140, 40, 40);
        seats.put(seat26, seat26.getName());

        seat27.setBackground(new java.awt.Color(204, 204, 204));
        seat27.setText("7");
        seat27.setName("seat27"); // NOI18N
        seat27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat27ActionPerformed(evt);
            }
        });
        getContentPane().add(seat27);
        seat27.setBounds(340, 140, 40, 40);
        seats.put(seat27, seat27.getName());

        seat28.setBackground(new java.awt.Color(204, 204, 204));
        seat28.setText("8");
        seat28.setName("seat28"); // NOI18N
        seat28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat28ActionPerformed(evt);
            }
        });
        getContentPane().add(seat28);
        seat28.setBounds(390, 140, 40, 40);
        seats.put(seat28, seat28.getName());

        seat29.setBackground(new java.awt.Color(204, 204, 204));
        seat29.setText("9");
        seat29.setName("seat29"); // NOI18N
        seat29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat29ActionPerformed(evt);
            }
        });
        getContentPane().add(seat29);
        seat29.setBounds(440, 140, 40, 40);
        seats.put(seat29, seat29.getName());

        seat210.setBackground(new java.awt.Color(204, 204, 204));
        seat210.setText("0");
        seat210.setName("seat210"); // NOI18N
        seat210.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat210ActionPerformed(evt);
            }
        });
        getContentPane().add(seat210);
        seat210.setBounds(490, 140, 40, 40);
        seats.put(seat210, seat210.getName());

        seat36.setBackground(new java.awt.Color(204, 204, 204));
        seat36.setText("6");
        seat36.setName("seat36"); // NOI18N
        seat36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat36ActionPerformed(evt);
            }
        });
        getContentPane().add(seat36);
        seat36.setBounds(290, 190, 40, 40);
        seats.put(seat36, seat36.getName());

        seat37.setBackground(new java.awt.Color(204, 204, 204));
        seat37.setText("7");
        seat37.setName("seat37"); // NOI18N
        seat37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat37ActionPerformed(evt);
            }
        });
        getContentPane().add(seat37);
        seat37.setBounds(340, 190, 40, 40);
        seats.put(seat37, seat37.getName());

        seat38.setBackground(new java.awt.Color(204, 204, 204));
        seat38.setText("8");
        seat38.setName("seat38"); // NOI18N
        seat38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat38ActionPerformed(evt);
            }
        });
        getContentPane().add(seat38);
        seat38.setBounds(390, 190, 40, 40);
        seats.put(seat38, seat38.getName());

        seat39.setBackground(new java.awt.Color(204, 204, 204));
        seat39.setText("9");
        seat39.setName("seat39"); // NOI18N
        seat39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat39ActionPerformed(evt);
            }
        });
        getContentPane().add(seat39);
        seat39.setBounds(440, 190, 40, 40);
        seats.put(seat39, seat39.getName());

        seat310.setBackground(new java.awt.Color(204, 204, 204));
        seat310.setText("0");
        seat310.setName("seat310"); // NOI18N
        seat310.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat310ActionPerformed(evt);
            }
        });
        getContentPane().add(seat310);
        seat310.setBounds(490, 190, 40, 40);
        seats.put(seat310, seat310.getName());

        seat46.setBackground(new java.awt.Color(204, 204, 204));
        seat46.setText("6");
        seat46.setName("seat46"); // NOI18N
        seat46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat46ActionPerformed(evt);
            }
        });
        getContentPane().add(seat46);
        seat46.setBounds(290, 240, 40, 40);
        seats.put(seat46,seat46.getName());

        seat47.setBackground(new java.awt.Color(204, 204, 204));
        seat47.setText("7");
        seat47.setName("seat47"); // NOI18N
        seat47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat47ActionPerformed(evt);
            }
        });
        getContentPane().add(seat47);
        seat47.setBounds(340, 240, 40, 40);
        seats.put(seat47,seat47.getName());

        seat48.setBackground(new java.awt.Color(204, 204, 204));
        seat48.setText("8");
        seat48.setName("seat48"); // NOI18N
        seat48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat48ActionPerformed(evt);
            }
        });
        getContentPane().add(seat48);
        seat48.setBounds(390, 240, 40, 40);
        seats.put(seat48,seat48.getName());

        seat49.setBackground(new java.awt.Color(204, 204, 204));
        seat49.setText("9");
        seat49.setName("seat49"); // NOI18N
        seat49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat49ActionPerformed(evt);
            }
        });
        getContentPane().add(seat49);
        seat49.setBounds(440, 240, 40, 40);
        seats.put(seat49,seat49.getName());

        seat410.setBackground(new java.awt.Color(204, 204, 204));
        seat410.setText("0");
        seat410.setName("seat410"); // NOI18N
        seat410.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat410ActionPerformed(evt);
            }
        });
        getContentPane().add(seat410);
        seat410.setBounds(490, 240, 40, 40);
        seats.put(seat410,seat410.getName());

        seat56.setBackground(new java.awt.Color(204, 204, 204));
        seat56.setText("6");
        seat56.setName("seat56"); // NOI18N
        seat56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat56ActionPerformed(evt);
            }
        });
        getContentPane().add(seat56);
        seat56.setBounds(290, 290, 40, 40);
        seats.put(seat56,seat56.getName());

        seat57.setBackground(new java.awt.Color(204, 204, 204));
        seat57.setText("7");
        seat57.setName("seat57"); // NOI18N
        seat57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat57ActionPerformed(evt);
            }
        });
        getContentPane().add(seat57);
        seat57.setBounds(340, 290, 40, 40);
        seats.put(seat57,seat57.getName());

        seat58.setBackground(new java.awt.Color(204, 204, 204));
        seat58.setText("8");
        seat58.setName("seat58"); // NOI18N
        seat58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat58ActionPerformed(evt);
            }
        });
        getContentPane().add(seat58);
        seat58.setBounds(390, 290, 40, 40);
        seats.put(seat58,seat58.getName());

        seat59.setBackground(new java.awt.Color(204, 204, 204));
        seat59.setText("9");
        seat59.setName("seat59"); // NOI18N
        seat59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat59ActionPerformed(evt);
            }
        });
        getContentPane().add(seat59);
        seat59.setBounds(440, 290, 40, 40);
        seats.put(seat59,seat59.getName());

        seat510.setBackground(new java.awt.Color(204, 204, 204));
        seat510.setText("0");
        seat510.setName("seat510"); // NOI18N
        seat510.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat510ActionPerformed(evt);
            }
        });
        getContentPane().add(seat510);
        seat510.setBounds(490, 290, 40, 40);
        seats.put(seat510,seat510.getName());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Seats : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 100, 60, 30);
        getContentPane().add(seatTextField);
        seatTextField.setBounds(618, 98, 190, 28);
        seatTextField.getAccessibleContext().setAccessibleName("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Price : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(540, 150, 52, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(618, 147, 98, 29);

        jButton51.setBackground(new java.awt.Color(102, 255, 102));
        jButton51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton51.setText("PAY");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton51);
        jButton51.setBounds(630, 210, 60, 30);

        seat61.setBackground(new java.awt.Color(204, 204, 204));
        seat61.setText("1");
        seat61.setName("seat61"); // NOI18N
        seat61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat61ActionPerformed(evt);
            }
        });
        getContentPane().add(seat61);
        seat61.setBounds(30, 340, 40, 40);
        seats.put(seat61,seat61.getName());

        seat62.setBackground(new java.awt.Color(204, 204, 204));
        seat62.setText("2");
        seat62.setName("seat62"); // NOI18N
        seat62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat62ActionPerformed(evt);
            }
        });
        getContentPane().add(seat62);
        seat62.setBounds(80, 340, 40, 40);
        seats.put(seat62,seat62.getName());

        seat63.setBackground(new java.awt.Color(204, 204, 204));
        seat63.setText("3");
        seat63.setName("seat63"); // NOI18N
        seat63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat63ActionPerformed(evt);
            }
        });
        getContentPane().add(seat63);
        seat63.setBounds(130, 340, 40, 40);
        seats.put(seat63,seat63.getName());

        seat64.setBackground(new java.awt.Color(204, 204, 204));
        seat64.setText("4");
        seat64.setName("seat64"); // NOI18N
        seat64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat64ActionPerformed(evt);
            }
        });
        getContentPane().add(seat64);
        seat64.setBounds(180, 340, 40, 40);
        seats.put(seat64,seat64.getName());

        seat65.setBackground(new java.awt.Color(204, 204, 204));
        seat65.setText("5");
        seat65.setName("seat65"); // NOI18N
        seat65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat65ActionPerformed(evt);
            }
        });
        getContentPane().add(seat65);
        seat65.setBounds(230, 340, 40, 40);
        seats.put(seat65,seat65.getName());

        seat66.setBackground(new java.awt.Color(204, 204, 204));
        seat66.setText("6");
        seat66.setName("seat66"); // NOI18N
        seat66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat66ActionPerformed(evt);
            }
        });
        getContentPane().add(seat66);
        seat66.setBounds(290, 340, 40, 40);
        seats.put(seat66,seat66.getName());

        seat67.setBackground(new java.awt.Color(204, 204, 204));
        seat67.setText("7");
        seat67.setName("seat67"); // NOI18N
        seat67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat67ActionPerformed(evt);
            }
        });
        getContentPane().add(seat67);
        seat67.setBounds(340, 340, 40, 40);
        seats.put(seat67,seat67.getName());

        seat68.setBackground(new java.awt.Color(204, 204, 204));
        seat68.setText("8");
        seat68.setName("seat68"); // NOI18N
        seat68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat68ActionPerformed(evt);
            }
        });
        getContentPane().add(seat68);
        seat68.setBounds(390, 340, 40, 40);
        seats.put(seat68,seat68.getName());

        seat69.setBackground(new java.awt.Color(204, 204, 204));
        seat69.setText("9");
        seat69.setName("seat69"); // NOI18N
        seat69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat69ActionPerformed(evt);
            }
        });
        getContentPane().add(seat69);
        seat69.setBounds(440, 340, 40, 40);
        seats.put(seat69,seat69.getName());

        seat610.setBackground(new java.awt.Color(204, 204, 204));
        seat610.setText("0");
        seat610.setName("seat610"); // NOI18N
        seat610.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat610ActionPerformed(evt);
            }
        });
        getContentPane().add(seat610);
        seat610.setBounds(490, 340, 40, 40);
        seats.put(seat610,seat610.getName());

        seat71.setBackground(new java.awt.Color(204, 204, 204));
        seat71.setText("1");
        seat71.setName("seat71"); // NOI18N
        seat71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat71ActionPerformed(evt);
            }
        });
        getContentPane().add(seat71);
        seat71.setBounds(80, 420, 40, 40);
        seats.put(seat71,seat71.getName());

        seat72.setBackground(new java.awt.Color(204, 204, 204));
        seat72.setText("2");
        seat72.setName("seat72"); // NOI18N
        seat72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat72ActionPerformed(evt);
            }
        });
        getContentPane().add(seat72);
        seat72.setBounds(130, 420, 40, 40);
        seats.put(seat72,seat72.getName());

        seat73.setBackground(new java.awt.Color(204, 204, 204));
        seat73.setText("3");
        seat73.setName("seat73"); // NOI18N
        seat73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat73ActionPerformed(evt);
            }
        });
        getContentPane().add(seat73);
        seat73.setBounds(180, 420, 40, 40);
        seats.put(seat73,seat73.getName());

        seat74.setBackground(new java.awt.Color(204, 204, 204));
        seat74.setText("4");
        seat74.setName("seat74"); // NOI18N
        seat74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat74ActionPerformed(evt);
            }
        });
        getContentPane().add(seat74);
        seat74.setBounds(230, 420, 40, 40);
        seats.put(seat74,seat74.getName());

        seat75.setBackground(new java.awt.Color(204, 204, 204));
        seat75.setText("5");
        seat75.setName("seat75"); // NOI18N
        seat75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat75ActionPerformed(evt);
            }
        });
        getContentPane().add(seat75);
        seat75.setBounds(290, 420, 40, 40);
        seats.put(seat75,seat75.getName());

        seat76.setBackground(new java.awt.Color(204, 204, 204));
        seat76.setText("6");
        seat76.setName("seat76"); // NOI18N
        seat76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat76ActionPerformed(evt);
            }
        });
        getContentPane().add(seat76);
        seat76.setBounds(340, 420, 40, 40);
        seats.put(seat76,seat76.getName());

        seat77.setBackground(new java.awt.Color(204, 204, 204));
        seat77.setText("7");
        seat77.setName("seat77"); // NOI18N
        seat77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat77ActionPerformed(evt);
            }
        });
        getContentPane().add(seat77);
        seat77.setBounds(390, 420, 40, 40);
        seats.put(seat77,seat77.getName());

        seat78.setBackground(new java.awt.Color(204, 204, 204));
        seat78.setText("8");
        seat78.setName("seat78"); // NOI18N
        seat78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat78ActionPerformed(evt);
            }
        });
        getContentPane().add(seat78);
        seat78.setBounds(440, 420, 40, 40);
        seats.put(seat78,seat78.getName());

        seat12.setBackground(new java.awt.Color(204, 204, 204));
        seat12.setText("2");
        seat12.setName("seat12"); // NOI18N
        seat12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat12ActionPerformed(evt);
            }
        });
        getContentPane().add(seat12);
        seat12.setBounds(80, 90, 40, 40);
        seats.put(seat12, seat12.getName());

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 20, 50, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\PROJECT\\TheatreBookingSystem\\ss\\bgbgbg.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, -4, 850, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    
    private void seat11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat11ActionPerformed
        selectUnSelect(seat11,100);
        if(seat11.isEnabled()==false){
            seat11.setOpaque(true);
            seat11.setBackground(Color.red);
        }
       
    }//GEN-LAST:event_seat11ActionPerformed

    private void seat13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat13ActionPerformed
        selectUnSelect(seat13,100);
        if(seat13.isEnabled()==false){
            seat13.setOpaque(true);
            seat13.setBackground(Color.red);
        }
        
    }//GEN-LAST:event_seat13ActionPerformed

    private void seat14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat14ActionPerformed
        selectUnSelect(seat14,100);
        if(seat14.isEnabled()==false){
            seat14.setOpaque(true);
            seat14.setBackground(Color.red);
        }
        
    }//GEN-LAST:event_seat14ActionPerformed

    private void seat15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat15ActionPerformed
        selectUnSelect(seat15,100);
        if(seat15.isEnabled()==false){
            seat15.setOpaque(true);
            seat15.setBackground(Color.red);
        }
        
    }//GEN-LAST:event_seat15ActionPerformed

    private void seat16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat16ActionPerformed
        selectUnSelect(seat16,100);
        if(seat16.isEnabled()==false){
            seat16.setOpaque(true);
            seat16.setBackground(Color.red);
        }
        
    }//GEN-LAST:event_seat16ActionPerformed

    private void seat17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat17ActionPerformed
        selectUnSelect(seat17,100);
        
    }//GEN-LAST:event_seat17ActionPerformed

    private void seat18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat18ActionPerformed
        selectUnSelect(seat18,100);
       
    }//GEN-LAST:event_seat18ActionPerformed

    private void seat19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat19ActionPerformed
        selectUnSelect(seat19,100);
        
    }//GEN-LAST:event_seat19ActionPerformed

    private void seat110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat110ActionPerformed
        selectUnSelect(seat110,100);
        
    }//GEN-LAST:event_seat110ActionPerformed

    private void seat21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat21ActionPerformed
        selectUnSelect(seat21,100);
        
    }//GEN-LAST:event_seat21ActionPerformed

    private void seat22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat22ActionPerformed
        selectUnSelect(seat22,100);
        
    }//GEN-LAST:event_seat22ActionPerformed

    private void seat23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat23ActionPerformed
        selectUnSelect(seat23,100);
        
    }//GEN-LAST:event_seat23ActionPerformed

    private void seat24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat24ActionPerformed
        selectUnSelect(seat24,100);
        
    }//GEN-LAST:event_seat24ActionPerformed

    private void seat25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat25ActionPerformed
        selectUnSelect(seat25,100);
        
    }//GEN-LAST:event_seat25ActionPerformed

    private void seat26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat26ActionPerformed
        selectUnSelect(seat26,100);
       
    }//GEN-LAST:event_seat26ActionPerformed

    private void seat27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat27ActionPerformed
        selectUnSelect(seat27,100);
        
    }//GEN-LAST:event_seat27ActionPerformed

    private void seat28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat28ActionPerformed
        selectUnSelect(seat28,100);
       
    }//GEN-LAST:event_seat28ActionPerformed

    private void seat29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat29ActionPerformed
       selectUnSelect(seat29,100);
       
    }//GEN-LAST:event_seat29ActionPerformed

    private void seat210ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat210ActionPerformed
        selectUnSelect(seat210,100);
        
    }//GEN-LAST:event_seat210ActionPerformed

    private void seat31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat31ActionPerformed
        selectUnSelect(seat31,100);
        
    }//GEN-LAST:event_seat31ActionPerformed

    private void seat32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat32ActionPerformed
        selectUnSelect(seat32,100);
        
    }//GEN-LAST:event_seat32ActionPerformed

    private void seat33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat33ActionPerformed
        selectUnSelect(seat33,100);
        
    }//GEN-LAST:event_seat33ActionPerformed

    private void seat34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat34ActionPerformed
       selectUnSelect(seat34,100);
       
    }//GEN-LAST:event_seat34ActionPerformed

    private void seat35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat35ActionPerformed
        selectUnSelect(seat35,100);
        
    }//GEN-LAST:event_seat35ActionPerformed

    private void seat36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat36ActionPerformed
        selectUnSelect(seat36,100);
        
    }//GEN-LAST:event_seat36ActionPerformed

    private void seat37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat37ActionPerformed
        selectUnSelect(seat37,100);
        
    }//GEN-LAST:event_seat37ActionPerformed

    private void seat38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat38ActionPerformed
        selectUnSelect(seat38,100);
        
    }//GEN-LAST:event_seat38ActionPerformed

    private void seat39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat39ActionPerformed
       selectUnSelect(seat39,100);
       
    }//GEN-LAST:event_seat39ActionPerformed

    private void seat310ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat310ActionPerformed
        selectUnSelect(seat310,100);
       
    }//GEN-LAST:event_seat310ActionPerformed
    
    private void seat41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat41ActionPerformed
        selectUnSelect(seat41,100);
        
    }//GEN-LAST:event_seat41ActionPerformed

    private void seat42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat42ActionPerformed
        selectUnSelect(seat42,100);
        
    }//GEN-LAST:event_seat42ActionPerformed

    private void seat43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat43ActionPerformed
        selectUnSelect(seat43,100);
        
    }//GEN-LAST:event_seat43ActionPerformed

    private void seat44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat44ActionPerformed
        selectUnSelect(seat44,100);
        
    }//GEN-LAST:event_seat44ActionPerformed

    private void seat45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat45ActionPerformed
        selectUnSelect(seat45,100);
        
    }//GEN-LAST:event_seat45ActionPerformed

    private void seat46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat46ActionPerformed
        selectUnSelect(seat46,100);
       
    }//GEN-LAST:event_seat46ActionPerformed

    private void seat47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat47ActionPerformed
        selectUnSelect(seat47,100);
        
    }//GEN-LAST:event_seat47ActionPerformed

    private void seat48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat48ActionPerformed
        selectUnSelect(seat48,100);
        
    }//GEN-LAST:event_seat48ActionPerformed

    private void seat49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat49ActionPerformed
        selectUnSelect(seat49,100);
        
    }//GEN-LAST:event_seat49ActionPerformed

    private void seat410ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat410ActionPerformed
        selectUnSelect(seat410,100);
        
    }//GEN-LAST:event_seat410ActionPerformed

    private void seat51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat51ActionPerformed
        selectUnSelect(seat51,100);
        
    }//GEN-LAST:event_seat51ActionPerformed

    private void seat52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat52ActionPerformed
        selectUnSelect(seat52,100);
        
    }//GEN-LAST:event_seat52ActionPerformed

    private void seat53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat53ActionPerformed
        selectUnSelect(seat53,100);
        
    }//GEN-LAST:event_seat53ActionPerformed

    private void seat54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat54ActionPerformed
        selectUnSelect(seat54,100);
        
    }//GEN-LAST:event_seat54ActionPerformed

    private void seat55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat55ActionPerformed
        selectUnSelect(seat55,100);
        
    }//GEN-LAST:event_seat55ActionPerformed

    private void seat56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat56ActionPerformed
        selectUnSelect(seat56,100);
        
    }//GEN-LAST:event_seat56ActionPerformed

    private void seat57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat57ActionPerformed
        selectUnSelect(seat57,100);
        
    }//GEN-LAST:event_seat57ActionPerformed

    private void seat58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat58ActionPerformed
        selectUnSelect(seat58,100);
        
    }//GEN-LAST:event_seat58ActionPerformed

    private void seat59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat59ActionPerformed
        selectUnSelect(seat59,100);
       
    }//GEN-LAST:event_seat59ActionPerformed

    private void seat510ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat510ActionPerformed
        selectUnSelect(seat510,100);
        
    }//GEN-LAST:event_seat510ActionPerformed

    private void seat61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat61ActionPerformed
        selectUnSelect(seat61,100);
        
    }//GEN-LAST:event_seat61ActionPerformed

    private void seat62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat62ActionPerformed
        selectUnSelect(seat62,100);
        
    }//GEN-LAST:event_seat62ActionPerformed

    private void seat63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat63ActionPerformed
        selectUnSelect(seat63,100);
        
    }//GEN-LAST:event_seat63ActionPerformed

    private void seat64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat64ActionPerformed
        selectUnSelect(seat64,100);
        
    }//GEN-LAST:event_seat64ActionPerformed

    private void seat65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat65ActionPerformed
       selectUnSelect(seat65,100);
       
    }//GEN-LAST:event_seat65ActionPerformed

    private void seat66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat66ActionPerformed
        selectUnSelect(seat66, 100);
        
    }//GEN-LAST:event_seat66ActionPerformed

    private void seat67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat67ActionPerformed
        selectUnSelect(seat67, 100);
        
    }//GEN-LAST:event_seat67ActionPerformed

    private void seat68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat68ActionPerformed
        selectUnSelect(seat68, 100);
        
    }//GEN-LAST:event_seat68ActionPerformed

    private void seat69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat69ActionPerformed
        selectUnSelect(seat69, 100);
        
    }//GEN-LAST:event_seat69ActionPerformed

    private void seat610ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat610ActionPerformed
        selectUnSelect(seat610, 100);
        
    }//GEN-LAST:event_seat610ActionPerformed

    private void seat71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat71ActionPerformed
        selectUnSelect(seat71, 350);
        
    }//GEN-LAST:event_seat71ActionPerformed

    private void seat72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat72ActionPerformed
        selectUnSelect(seat72, 350);
        
    }//GEN-LAST:event_seat72ActionPerformed

    private void seat73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat73ActionPerformed
        selectUnSelect(seat73, 350);
        
    }//GEN-LAST:event_seat73ActionPerformed

    private void seat74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat74ActionPerformed
        selectUnSelect(seat74, 350);
        
    }//GEN-LAST:event_seat74ActionPerformed

    private void seat75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat75ActionPerformed
        selectUnSelect(seat75, 350);
       
    }//GEN-LAST:event_seat75ActionPerformed

    private void seat76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat76ActionPerformed
        selectUnSelect(seat76, 350);
        
    }//GEN-LAST:event_seat76ActionPerformed

    private void seat77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat77ActionPerformed
        selectUnSelect(seat77, 350);
        
    }//GEN-LAST:event_seat77ActionPerformed

    private void seat78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat78ActionPerformed
        selectUnSelect(seat78, 350);
        
    }//GEN-LAST:event_seat78ActionPerformed

    
    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
       String _user = LoginUI.usertext.getText();
       String _movie = MovieCollection.movie_Name;
       
       int _userid = 0;
       int _movieid = 0;
       
       System.out.println("out of zone : "+_user+ _movie);
       
       
        try {
            String query1 = "select * from user where username=?";
            Connection connection = DriverManager.getConnection(url,username,password);
            PreparedStatement psmt1 = connection.prepareStatement(query1);
            psmt1.setString(1,_user);
            ResultSet rs = psmt1.executeQuery();
            if(rs.next()){
                _userid = rs.getInt("user_id");
            }
            
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(rootPane, "ERROR IN FINDING USER ID");
        }
        
        try{
            String query2 = "select * from Movies where movie_name=?";
            Connection con2 = DriverManager.getConnection(url,username,password);
            PreparedStatement ps1 = con2.prepareStatement(query2);
            ps1.setString(1,_movie);
            ResultSet rs1 = ps1.executeQuery();
            
            if(rs1.next()){
               _movieid = rs1.getInt("movie_id");
            }
            
        }catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showConfirmDialog(rootPane, "ERROR IN FINDING MOVIE ID");
        }
        
        try{
            String query = "insert into seatbook (USERID,MOVIEID,SEATNAMES,TIMEDATE) values(?,?,?,?)";
            Connection con1 = DriverManager.getConnection(url,username,password);
            PreparedStatement ps = con1.prepareStatement(query);
            System.out.println("insert into seatbook _movieID : "+_movieid);
            
            Timestamp temptime1 = new Timestamp(System.currentTimeMillis());
            
            for(Map.Entry<Timestamp,String> entry : MovieCollection.map.entrySet()){
                if(entry.getValue().equals(MovieCollection.jComboBox1.getSelectedItem())){
                    temptime1 = entry.getKey();
                } 
            }
            
            ps.setInt(1,_userid);
            ps.setInt(2,_movieid);
            ps.setTimestamp(4,temptime1);
            for(JButton b : buttons){
                ps.setString(3, b.getName());
                 ps.execute();
            }
//            ps.setString(3,seatTextField.getText().trim());
            
           
            String str[]  = seatTextField.getText().trim().split(" ");
            for(JButton b : buttons){
                for(Map.Entry<JButton,String> entry : seats.entrySet()){
                    if(entry.getKey().equals(b)){
                        entry.getKey().repaint();
                        entry.getKey().revalidate();
                         entry.getKey().setBackground(Color.red);
//                        entry.getKey().setOpaque(true);
                         entry.getKey().setBorderPainted(false);
                        entry.getKey().setEnabled(false);
                    }
            }
            }
                   
            
        }catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showConfirmDialog(rootPane, "INSERT METHOD IS WRONG");
            
        }
        
        try{
            String query  = "INSERT INTO payment(pay_cus_id,pay_amount,movieid) values(?,?,?)";
            Connection con = DriverManager.getConnection(url,username,password);
            PreparedStatement psmt = con.prepareStatement(query);
          
            psmt.setInt(1,_userid);
            psmt.setInt(2,Integer.parseInt(jTextField2.getText()));
            psmt.setInt(3,MovieCollection._movieid);
            psmt.execute();
            JOptionPane.showMessageDialog(rootPane,"Your Payement is success Fully Finished :)");
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"Add Data into payement has error");
        }
        
     
        
    }//GEN-LAST:event_jButton51ActionPerformed

    private void seat12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat12ActionPerformed
        // TODO add your handling code here:
        selectUnSelect(seat12, 100);
    }//GEN-LAST:event_seat12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new MovieCollection().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatBook().setVisible(true);
            }
        });
        
    }
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton51;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private static javax.swing.JTextField jTextField2;
    public javax.swing.JButton seat11;
    public javax.swing.JButton seat110;
    public javax.swing.JButton seat12;
    public javax.swing.JButton seat13;
    public static javax.swing.JButton seat14;
    public static javax.swing.JButton seat15;
    public javax.swing.JButton seat16;
    public javax.swing.JButton seat17;
    public javax.swing.JButton seat18;
    public javax.swing.JButton seat19;
    public javax.swing.JButton seat21;
    public javax.swing.JButton seat210;
    public javax.swing.JButton seat22;
    public javax.swing.JButton seat23;
    public javax.swing.JButton seat24;
    public javax.swing.JButton seat25;
    public javax.swing.JButton seat26;
    public javax.swing.JButton seat27;
    public javax.swing.JButton seat28;
    public javax.swing.JButton seat29;
    private javax.swing.JButton seat31;
    private javax.swing.JButton seat310;
    private javax.swing.JButton seat32;
    private javax.swing.JButton seat33;
    private javax.swing.JButton seat34;
    private javax.swing.JButton seat35;
    private javax.swing.JButton seat36;
    private javax.swing.JButton seat37;
    private javax.swing.JButton seat38;
    private javax.swing.JButton seat39;
    private javax.swing.JButton seat41;
    private javax.swing.JButton seat410;
    private javax.swing.JButton seat42;
    private javax.swing.JButton seat43;
    private javax.swing.JButton seat44;
    private javax.swing.JButton seat45;
    private javax.swing.JButton seat46;
    private javax.swing.JButton seat47;
    private javax.swing.JButton seat48;
    private javax.swing.JButton seat49;
    private javax.swing.JButton seat51;
    private javax.swing.JButton seat510;
    private javax.swing.JButton seat52;
    private javax.swing.JButton seat53;
    private javax.swing.JButton seat54;
    private javax.swing.JButton seat55;
    private javax.swing.JButton seat56;
    private javax.swing.JButton seat57;
    private javax.swing.JButton seat58;
    private javax.swing.JButton seat59;
    private javax.swing.JButton seat61;
    private javax.swing.JButton seat610;
    private javax.swing.JButton seat62;
    private javax.swing.JButton seat63;
    private javax.swing.JButton seat64;
    private static javax.swing.JButton seat65;
    private javax.swing.JButton seat66;
    private javax.swing.JButton seat67;
    private javax.swing.JButton seat68;
    private javax.swing.JButton seat69;
    private javax.swing.JButton seat71;
    private javax.swing.JButton seat72;
    private javax.swing.JButton seat73;
    private javax.swing.JButton seat74;
    private javax.swing.JButton seat75;
    private javax.swing.JButton seat76;
    private javax.swing.JButton seat77;
    private javax.swing.JButton seat78;
    private static javax.swing.JTextField seatTextField;
    // End of variables declaration//GEN-END:variables




    public static void showSeatNames(ArrayList<String> seat){
        String sentence = " ";
        for(String s : seat){
            sentence = s +" "+sentence;
        }
        seatTextField.setText(sentence);
    }


    
    
    
    
    
    
}
